server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: usuarios-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/usuarios_db?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:autoservice}
    password: ${SPRING_DATASOURCE_PASSWORD:autoservice}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false

security:
  jwt:
    secret: '${JWT_SECRET:AutoService2026SuperSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong!!}'
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:1800}

app:
  seed:
    admin-password: ${ADMIN_PASSWORD:admin123}
    recepcion-password: ${RECEPCION_PASSWORD:recepcion123}
    mecanico-password: ${MECANICO_PASSWORD:mecanico123}
    facturacion-password: ${FACTURACION_PASSWORD:facturacion123}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
