server:
  port: 8086

spring:
  application:
    name: facturacion-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=facturacion_db;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: crpp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

clientes:
  ordenes:
    url: ${ORDENES_SERVICE_URL:http://localhost:8084}
