server:
  port: 8084

spring:
  application:
    name: ordenes-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ordenes_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: crpp
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

services:
  vehiculos:
    url: ${CLIENTES_VEHICULOS_SERVICE_URL:http://localhost:8082}

  clientes:
    url: ${CLIENTES_VEHICULOS_SERVICE_URL:http://localhost:8082}

  inventario:
    url: ${INVENTARIO_SERVICE_URL:http://localhost:8085}

  usuarios:
    url: ${USUARIOS_SERVICE_URL:http://localhost:8081}

app:
  kafka:
    topic:
      ordenes: ordenes-events

logging:
  level:
    com.autoservice.ordenes: debug
    org.hibernate.SQL: debug
